Fix Bazel 9 crash when using `file:///` (#135)
This resolves a Bazel crash
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@@+requirements2+req_compile_test_find_links__pyspark' (requested by nodes 'PACKAGE_LOOKUP:@@+requirements2+req_compile_test_find_links__pyspark//')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:552)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: NullPointerException thrown during Starlark evaluation (repository @@+requirements2+req_compile_test_find_links__pyspark)
	at <starlark>.download(<builtin>:0)
	at <starlark>._whl_repository_impl(/Users/user/Code/req-compile/private/whl_repo.bzl:264)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.net.URI.getHost()" is null
	at com.google.devtools.build.lib.bazel.repository.downloader.ProgressInputStream.reportProgress(ProgressInputStream.java:139)
	at com.google.devtools.build.lib.bazel.repository.downloader.ProgressInputStream.read(ProgressInputStream.java:117)
	at com.google.devtools.build.lib.bazel.repository.downloader.HashInputStream.read(HashInputStream.java:62)
	at java.base/java.io.SequenceInputStream.read(Unknown Source)
	at java.base/java.io.FilterInputStream.read(Unknown Source)
	at java.base/java.io.InputStream.transferTo(Unknown Source)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:101)
	at com.google.devtools.build.lib.bazel.repository.downloader.DelegatingDownloader.download(DelegatingDownloader.java:64)
	at com.google.devtools.build.lib.bazel.repository.downloader.DownloadManager.downloadInExecutor(DownloadManager.java:333)
	at com.google.devtools.build.lib.bazel.repository.downloader.DownloadManager.lambda$startDownload$0(DownloadManager.java:143)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$ThreadBoundFuture.run(Unknown Source)
	at java.base/java.lang.VirtualThread.run(Unknown Source)
	Suppressed: com.google.devtools.build.lib.bazel.repository.downloader.ContentLengthMismatchException: Bytes read 80953344 but wanted 317488491
		at com.google.devtools.build.lib.bazel.repository.downloader.CheckContentLengthInputStream.checkContentLength(CheckContentLengthInputStream.java:71)
		at com.google.devtools.build.lib.bazel.repository.downloader.CheckContentLengthInputStream.close(CheckContentLengthInputStream.java:66)
		at com.google.devtools.build.lib.bazel.repository.downloader.ProgressInputStream.close(ProgressInputStream.java:129)
		at com.google.devtools.build.lib.bazel.repository.downloader.HashInputStream.close(HashInputStream.java:78)
		at java.base/java.io.SequenceInputStream.close(Unknown Source)
		at java.base/java.io.FilterInputStream.close(Unknown Source)
		at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:98)
		... 6 more
```